// ABOUTME: Exposes cash flows API handlers to Next.js routing.
// ABOUTME: Re-exports verb handlers generated by the factory.
import { createCashFlowsHandler } from "./cash-flows-handler";

const handlers = createCashFlowsHandler();

export const GET = handlers.GET;
export const POST = handlers.POST;
